SARFish_root_directory: /mnt/h/SARFish/
xView3_SLC_GRD_correspondences_path: /home/peterm/UWA/CITS5014/SARFish/working/labels/xView3_SLC_GRD_correspondences.csv
product_type: SLC

FOLD:
    FoldCSV: fold.csv
    WhichFold: 1

CREATE_TILE:
    TileSize: 1024
    TileOverlap: 64
    TilePath: extracted_slc_tile/

TRAIN:
    TrainedModelPath: trained_model/
    TensorBoardFolder: tb_log/
    BatchSize: 8
    NumberEpochs: 20
    ModelSavingFreq: 5

TEST:
    ScoreThreshold: 0.3
    EpochToUse: 19
