data_paths:
  SARFish_root_directory:
    local:              /mnt/h/SARFish/SLC/validation/
    kaya:               /group/pmc044/data/SARFish/SLC/validation/

  Generated_root_directory: 
    local:              /mnt/h/SARFish/Generated/
    kaya:               /group/pmc044/data/Generated/

product_type:           SLC

create_crop:
  correspondences_path: 'xView3_SLC_GRD_correspondences.csv'
  annotations_path:     ./SARFish_labels/validation/SLC/SLC_validation_labels.csv
  arrays_path:          SLC/train/arrays_raw/
  crop_path:            SLC/train/crops/
  crop_size:            96
  label_confidence:     ['HIGH', 'MEDIUM']
  quiet_mode:           True

batch_sar_processing:
  input_dir:            SLC/train/crops/images/
  output_dir:           SLC/train/crops/images_proc/
  script_path:          'complex_scale_and_norm.py'
  nan_strategy:         skip
  epsilon:              1e-6
  verbose:              False
  global_norm_params:   [0.0, 70.0]  # or null for adaptive
  max_workers:          4  # or null for sequential
  file_pattern:         '*.npy'
  skip_existing:        True
  log_file:             'batch_sar_processing.log'  # or null to disable
