data_paths:
  SARFish_root_directory:
    local:              /mnt/h/SARFish/SLC/validation/
    kaya:               /group/pmc044/data/SARFish/SLC/validation/

  Generated_root_directory: 
    local:              /mnt/h/SARFish/Generated/SLC/
    kaya:               /group/pmc044/data/Generated/SLC/

  arrays_path:
    train:              train/arrays_raw/
    val:                val/arrays_raw/
    test:               test/arrays_raw/

product_type:           SLC

create_crop:
  correspondences_path: 'xView3_SLC_GRD_correspondences.csv'
  annotations_path:     ./SARFish_labels/validation/SLC/SLC_validation_labels.csv
  crop_path:
    train:              train/crops_raw_96s/
    val:                val/crops_raw_96s/
    test:               test/crops_raw_96s/
  crop_size:            96 
  use_spatial_indexing: True
  min_crop_distance:    48
  label_confidence:     ['HIGH', 'MEDIUM']
  quiet_mode:           True

batch_sar_processing:
  input_dir:
    train:              train/crops_raw/images/  # use crops_aug for augmented training crops
    val:                val/crops_raw/images/ 
    test:               test/crops_raw/images/
  output_dir:
    train:              train/crops_prc/images/
    val:                val/crops_prc/images/
    test:               test/crops_prc/images/
  script_path:          'complex_scale_and_norm.py'
  nan_strategy:         skip
  epsilon:              1e-6
  verbose:              False
  max_workers:          4  # or null for sequential
  file_pattern:         '*.npy'
  skip_existing:        True
  log_file:             'batch_sar_processing.log'  # or null to disable
