data_paths:
  SARFish_root_directory:
    local:              /mnt/h/SARFish/SLC/validation/
    kaya:               /group/pmc044/data/SARFish/SLC/validation/

  Generated_root_directory: 
    local:              /mnt/h/SARFish/Generated/
    kaya:               /group/pmc044/data/Generated/

  arrays_path:
    train:              SLC/train/arrays_raw/
    val:                SLC/val/arrays_raw/
    test:               SLC/test/arrays_raw/

product_type:           SLC

create_crop:
  correspondences_path: 'xView3_SLC_GRD_correspondences.csv'
  annotations_path:     ./SARFish_labels/validation/SLC/SLC_validation_labels.csv
  crop_path:
    train:              SLC/train/crops/
    val:                SLC/val/crops/
    test:               SLC/test/crops/
  crop_size:            96 
  use_spatial_indexing: False
  min_crop_distance:    512
  label_confidence:     ['HIGH', 'MEDIUM']
  quiet_mode:           True

batch_sar_processing:
  input_dir:
    train:              SLC/train/crops/images
    val:                SLC/val/crops/images
    test:               SLC/test/crops/images
  output_dir:
    train:              SLC/train/crops/images_proc
    val:                SLC/val/crops/images_proc
    test:               SLC/test/crops/images_proc
  script_path:          'complex_scale_and_norm.py'
  nan_strategy:         skip
  epsilon:              1e-6
  verbose:              False
  global_norm_params:   [0.0, 71.5]  # raw amplitude percentile clipped (1st, 99th); null for adaptive
  max_workers:          4  # or null for sequential
  file_pattern:         '*.npy'
  skip_existing:        True
  log_file:             'batch_sar_processing.log'  # or null to disable
